### ISSUE TITLE
Fix travis-ci tests

### ISSUE THREAD

**Issue by AlmogBaku** [Spomky-Labs/OAuth2ServerBundle#17]
Currently all of them failed :(

**Comment by Spomky** [comment]
Yes they fail.
This is mainly due to unstable dependencies [jose](https://github.com/Spomky-Labs/jose), [JoseBundle](https://github.com/Spomky-Labs/JoseBundle) and the [oauth2-server-library](https://github.com/Spomky-Labs/oauth2-server-library).
[jose](https://github.com/Spomky-Labs/jose) and [JoseBundle](https://github.com/Spomky-Labs/JoseBundle) projects should become stable within the next days.
Then I will update the library and this bundle.

**Comment by AlmogBaku** [comment]
BTW, what's the difference between JOSE and other existing jwt projects(such as lcobucci/jwt )?
I afraid it'll be hard to maintain all this project :O

**Comment by Spomky** [comment]
All other JWT libraries do the same job.
[I participated to the `namshi/jose` library](https://github.com/namshi/jose/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3ASpomky), but I was a little bit frustrated because this library (and all other libraries) only implement JWS (signed JWT) and few algorithms (HMAC and RSA in general).
Most of the changes I aimed to submit would imply BC breaks. That is why I decided to create my own project.
ATM, my library implements almost all specifications proposed by the associated RFCs (JWK, JKWSet, JWS, JWE), including all encryption/signature algorithms.

You are right, this is quite difficult to maintain, but I am motivated, [especially when I receive encouragement from people interested in my projects](https://github.com/Spomky-Labs/jose/issues/32#issue-102755217).
There are on-going discussions to decide to integrate these projects to the FirendsOfSymfony team. Alan Bem, one of the maintainer of the FosOAuthBundle proposed my to the team as new maintainer. So yes, I am alone for the start of this project, but with such team and all contributors (you included) it should be easier to maintain in the futur.

**Comment by AlmogBaku** [comment]
:+1: Keep the great work.
I'm highly considering integrating to your project instead of the FOS ones. :)

**Comment by Spomky** [comment]
Hi,

Fisrt of all, thank you for the consideration you have on this project.

I recently updated the project and the associated libraries. The tests still fail, but it is mainly due to `Puli` [that is not yet available on Symfony3](https://github.com/puli/symfony-bundle/pull/19).
Concerning other tests, I am investigating. However, they seem to fail because of the test I wrote.

**Comment by Spomky** [comment]
Waiting for https://github.com/puli/symfony-bundle/pull/19 to be merged for tests to pass.

**Comment by Spomky** [comment]
Now all tests passed. It comprises HHVM and PHP 5.5.9+/7.0+ on Symfony 2.7+/3.0+.
Next weeks will be dedicated on the stabilization of the bundle and other improvements.
